
# After registering a name on build.snapcraft.io, commit an uncommented line:
name: mtcnn-light-cpp
version: '0.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: MTCNN network with no framework to detect human face # 79 char long summary
description: |
  this repository is the implementation of MTCNN with no framework, Just need opencv and openblas,implemented with C++，
  no framework.
  it is very easy for you to use.it is can be a part of your project with no framework, like caffe and mxnet.
  it is real time for VGA, and you can improve it's runtime.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mtcnn-light-cpp:
    # See 'snapcraft plugins'
    plugin: cmake
    source-type: git
    source: https://github.com/wmatrix/MTCNN-light.git
    build-packages:
      - g++
      - make
      - cmake
      - libopencv-dev
      - libopenblas-dev
  
